version: '3.8'

services:
  web:
    build: .
    command: bash -c 'bash /docker-test/pre-start.sh'
    volumes:
      - .:/docker-test
    ports:
      - 8008:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data/
      - /tmp/backups:/tmp/backups
    expose:
      - 5432

volumes:
  db: